{
	"version": 1710428011,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/hitam_menu-sheet0.png",
		"images/c-sheet0.png",
		"images/d-sheet0.png",
		"images/b-sheet0.png",
		"images/spritefont.png",
		"images/sprite-sheet0.png",
		"images/a-sheet0.png",
		"images/bg_0-sheet0.png",
		"images/sekarrare-sheet0.png",
		"images/icon_goakmaling-sheet0.png",
		"images/icon_ketutgaring-sheet0.png",
		"images/icon_madecenik-sheet0.png",
		"images/icon_uban-sheet0.png",
		"images/icon_meong-sheet0.png",
		"images/icon_anom-sheet0.png",
		"images/poppenjelasan-sheet0.png",
		"images/lirikrare-sheet0.png",
		"images/lirikrare-sheet1.png",
		"images/lirikrare-sheet2.png",
		"images/kaset_ketutgaring-sheet0.png",
		"images/playkaset_ketutgaring-sheet0.png",
		"images/playkaset_ketutgaring-sheet1.png",
		"images/close_lagu-sheet0.png",
		"images/indo-sheet0.png",
		"images/bali-sheet0.png",
		"images/aksarabali-sheet0.png",
		"images/kaset_ratu-sheet0.png",
		"images/kaset_meong-sheet0.png",
		"images/kaset_jenggotuban-sheet0.png",
		"images/kaset_goakmaling-sheet0.png",
		"images/kaset_madecenik-sheet0.png",
		"images/kembali-sheet0.png",
		"media/button.ogg",
		"media/select.ogg",
		"media/button.m4a",
		"media/select.m4a",
		"media/tombol.m4a",
		"media/tombol.ogg",
		"media/goak maling.m4a",
		"media/goak maling.ogg",
		"media/jengot uban.m4a",
		"media/jengot uban.ogg",
		"media/ketut garing.m4a",
		"media/ketut garing.ogg",
		"media/made cenik.m4a",
		"media/made cenik.ogg",
		"media/meong meong.m4a",
		"media/meong meong.ogg",
		"media/ratu anom.m4a",
		"media/ratu anom.ogg",
		"media/sub_lagu.m4a",
		"media/sub_lagu.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}